from __future__ import annotations

import os
from pathlib import Path


BUILD_INFO_PATH = Path("src/intrastat_generator/_build_info.py")


def build_info_text(version: str, branch: str) -> str:
    return (
        "# Generated by the release workflow. Local source keeps blank defaults.\n"
        f"BUILD_VERSION = {version!r}\n"
        f"BUILD_BRANCH = {branch!r}\n"
    )


def main() -> int:
    version = os.environ.get("INTRASTAT_GENERATOR_VERSION", "").strip()
    branch = os.environ.get("INTRASTAT_GENERATOR_BRANCH", "").strip()
    BUILD_INFO_PATH.write_text(build_info_text(version, branch), encoding="utf-8")
    print(f"Embedded build version: {version or '<empty>'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
